name: 'football_data_analytics'
version: '1.0.0'

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  football_data_analytics:
    sources:
      materialized: view
      enabled: true
    transformations:
      materialized: table
      enabled: true
    final:
      materialized: table
      enabled: true

seeds:
  football_data_analytics:
    enabled: true
    materialized: table

snapshots:
  football_data_analytics:
    enabled: true

tests:
  football_data_analytics:
    enabled: true